# Generated by Django 5.1.4 on 2025-01-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category_type',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Desktop Application', 'Desktop Application'), ('Data Science', 'Data Science'), ('Android Application', 'Mobile App'), ('IOS Application', 'IOS Mobile App')], max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
